spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${okta.oauth2.issuer}

  cloud:
    gateway:
      httpclient:
        response-timeout: 20s
        connect-timeout: 5000
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

okta:
  oauth2:
    issuer: ${OKTA_ISSUER:https://dev-uohbym6z6fckx48b.us.auth0.com/}
    client-id: ${OKTA_CLIENT_ID:Vq9wCKt7getxnBS2sNbUgqXpfgUTgPb9}
    client-secret: ${OKTA_CLIENT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: ["health", "routes", "gateway", "metrics", "info"]
  info:
    env:
      enabled: true
info:
  app:
    name: api-gateway

#logging:
#  level:
#    application: debug
#    org.springframework.cloud.gateway.filter: debug
#    org.springframework.cloud.gateway: debug
#    io.github.resilience4j: debug
#    org.springframework.web: debug
#    org.springframework.security: debug
#    org.springframework.security.web: debug
#    org.springframework.web.cors: debug
#    org.springframework.web.filter.CorsFilter: debug